# Generated by Django 4.2.1 on 2023-05-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='hard_disk_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='printer_purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='system_purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='device_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=120, null=True)),
                ('sys_name', models.CharField(blank=True, max_length=120, null=True)),
                ('processor', models.CharField(blank=True, max_length=120, null=True)),
                ('ram', models.CharField(blank=True, max_length=5, null=True)),
                ('hard_disk_size', models.CharField(blank=True, max_length=120, null=True)),
                ('monitor', models.CharField(blank=True, max_length=120, null=True)),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('printer_year', models.CharField(max_length=5, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.branch')),
                ('hard_disk_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.hard_disk_type')),
                ('manufacture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.manufacture')),
                ('printer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.printer')),
                ('printer_purchased_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.printer_purchased')),
                ('system_purchased_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.system_purchased')),
            ],
        ),
    ]
