# Generated by Django 4.2.1 on 2023-05-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_list',
            name='system_purchased_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device_list',
            name='printer_year',
            field=models.DateField(null=True),
        ),
    ]
