# Generated by Django 4.2.1 on 2023-05-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_device_list_system_purchased_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_list',
            name='printer_purchased_from',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='device_list',
            name='system_purchased_from',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='printer_purchased',
        ),
        migrations.DeleteModel(
            name='system_purchased',
        ),
    ]
