# Generated by Django 4.2.1 on 2023-05-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_alter_device_list_printer_purchased_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_list',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.printer'),
        ),
        migrations.AlterField(
            model_name='device_list',
            name='printer_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
