# Generated by Django 4.2.1 on 2023-05-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_alter_device_list_printer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_list',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes'),
        ),
    ]
