# Generated by Django 2.2.28 on 2023-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0006_auto_20230529_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_list',
            name='barcode_filename',
        ),
        migrations.AddField(
            model_name='device_list',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
