# Generated by Django 2.2.28 on 2023-05-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_auto_20230530_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_list',
            name='barcode',
        ),
    ]
