# Generated by Django 2.2.28 on 2023-05-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_remove_device_list_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_list',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
